### ISSUE TITLE
Suggestion: move mimikatz compiled blob in a second file

### ISSUE THREAD

**Issue by cnotin** [GhostPack/SafetyKatz#1]
The mimikatz compiled blob in the `compressedString` variable makes Visual Studio slow and laggy when scrolling the code or debugging in step-by-step.
To prevent this, I suggest moving this blob to a second file (e.g. `Constants.cs`)

**Comment by HarmJ0y** [comment]
Should be resolved with https://github.com/GhostPack/SafetyKatz/commit/715b311f76eb3a4c8d00a1bd29c6cd1899e450b7
